#ifndef CODEWARS_C_SOLUTION_NEXT_SMALLER_PRONIC_H
#define CODEWARS_C_SOLUTION_NEXT_SMALLER_PRONIC_H

unsigned long long next_smaller_pronic(unsigned long long number);

#endif //CODEWARS_C_SOLUTION_NEXT_SMALLER_PRONIC_H