"""https://www.codewars.com/kata/5a25ac6ac5e284cfbe000111"""

from utils_anviks import stopwatch


@stopwatch
def triangle(row: str):
    chunk_sizes = (3 ** i + 1 for i in range(9, -1, -1))
    mapper = {'R': 0, 0: 'R', 'G': 1, 1: 'G', 'B': 2, 2: 'B'}
    row = [mapper[char] for char in row]
    
    for size in chunk_sizes:
        while len(row) >= size:
            new_row = []
            
            for i in range(len(row) - size + 1):
                if row[i] == row[i + size - 1]:
                    new_row.append(row[i])
                else:
                    new_row.append(3 - row[i] - row[i + size - 1])
                    
            row = new_row
            
    return mapper[row[0]]


def main():
    print(triangle('GB'), 'R')
    print(triangle('RRR'), 'R')
    print(triangle('RGBG'), 'B')
    print(triangle('RBRGBRB'), 'G')
    print(triangle('RBRGBRBGGRRRBGBBBG'), 'G')
    print(triangle('BBRGBRBGGGRG'))
    print(triangle('BBRGBRBGGGG'))
    print(triangle('BBRGBRBGGG'))
    print(
        triangle('GRRBRRGGGGGGBBGBRRGRRGBGGRBBGBBGBRRBGBBGGBRRRRRGBBBBRRGBRBBBBBGGRBGBBRRRGRRBBGGBRBRGBRGRGGGGGRRBRG'))
    print(triangle('B'), 'B')
    print(triangle(
        'BRRBRRGGGGGGBBGBRRGRRGBGGRBBGBBGBRRBGBBGGBRRRRRGBBBBRRGBRBBBBBGGRBGBBRRRGRRBBGGBRBRGBRGRGGGGGRRBRGGBRBRBBGGGRBGRRBRBBRRBRBGBGBRRGGBRGRGBGRGBBBRRGBRRGGGRRBRRBRGRBRBBGBGGGBGRBRGRBGRBGRRRBRGRBGBGRRBBRGBRBRRGRRGGGGBGBBGRRGBGGGRBBGGBBBGRRBBGRBRBBRBRGGGBRRGRGRRRGBGBBRGRGBGGGBBRRRGRRBRBGGBBRGB'))
    print(triangle(
        'RRGRRRRGRGBRRRBBRGGBRBRGRBBBGBRGRBRBBBGBRRGRRGBGRBGBGBRRRRGRBGBBGBBGBRRBRRGBRRGBBGGRGGRRBBRRRRRGRRBBBBBRGRGRGBBGGBBGRGRRGRGBGBGRBBBGGRGGBGRBBRBGGBGRBRBRRGRRRGRRGGRRGRRGBGBRBRBGBRRGGRRBBGBGBBBRGGRRRBRBRBGGRGBRBGRRRRRRRBGBGBGRGBRGGGBGRGGRGGRGRBRRGBGGGRGRRRBBBRRBGRBBRRGRBBGRGBRGRGGRRRGRRGGBGBBGBGBGRGGBBBGRBBGRBRGGBGRBBGBGBBGGGRBGGGRGGGRGBGRGBBBBRGRRRRGRGRBRBGBRRBGBGRBGGRGRRRBRRGRBBGBGGBBRBBGRGBBGBGRGRRRBRRRRBBRGGGBRBGGBBRBGGRRGGRBGRBRGBGRRGRRBBBGBBBGRBRRBRBBGBRBBBRRGGGBBBRRGRRBRRRBRGRGGRBBRGBGRRBRBRGGBGRBGBBBGGGRGBRBRGGRBRRRGRRGBBGBBRRGGGGGRBGRGRBRGGGBBRBRBGGRBGRGBRRRGGGBBBGGGBGGBRRBBGRGBBRGBGBGGBGGBRRGGGGBRRBGBGRBGBRBRGRBRBBGRGBRRBBBRGGBRBGBBGBBGBBBRBBGGGBGRGBBBRRBBBRBBGRBGBRGBRRBRGBBBBBBBGGBBRGRBBRBRGRGGRGBBBRBGBRGRG'))
    print(triangle(
        'RRGRRRRGRGBRRRBBRGGBRRGRBBBGBRGRBRBBBGBRRGRRGBGRBGBGBRRRRGRBGBBGBBGBRRBRRGBRRGBBGGRGGRRBBRRRRRGRRBBBBBRGRGRGBBGGBBGRGRRGRGBGBGRBBBGGRGGBGRBBRBGGBGRBRBRRGRRRGRRGGRRGRRGBGBRBRBGBRRGGRRBBGBGBBBRGGRRRBRBRBGGRGBRBGRRRRRRRBGBGBGRGBRGGGBGRGGRGGRGRBRRGBGGGRGRRRBBBRRBGRBBRRGRBBGRGBRGRGGRRRGRRGGBGBBGBGBGRGGBBBGRBBGRBRGGBGRBBGBGBBGGGRBGGGRGGGRGBGRGBBBBRGRRRRGRGRBRBGBRRBGBGRBGGRGRRRBRRGRBBGBGGBBRBBGRGBBGBGRGRRRBRRRRBBRGGGBRBGGBBRBGGRRGGRBGRBRGBGRRGRRBBBGBBBGRBRRBRBBGBRBBBRRGGGBBBRRGRRBRRRBRGRGGRBBRGBGRRBRBRGGBGRBGBBBGGGRGBRBRGGRBRRRGRRGBBGBBRRGGGGGRBGRGRBRGGGBBRBRBGGRBGRGBRRRGGGBBBGGGBGGBRRBBGRGBBRGBGBGGBGGBRRGGGGBRRBGBGRBGBRBRGRBRBBGRGBRRBBBRGGBRBGBBGBBGBBBRBBGGGBGRGBBBRRBBBRBBGRBGBRGBRRBRGBBBBBBBGGBBRGRBBRBRGRGGRGBBBRBGBRGRG'))


if __name__ == '__main__':
    main()
