#ifndef CODEWARS_C_SOLUTION_MULTIPLYING_NUMBERS_AS_STRINGS_H
#define CODEWARS_C_SOLUTION_MULTIPLYING_NUMBERS_AS_STRINGS_H
    
char* multiply(const char* a, const char* b);

#endif //CODEWARS_C_SOLUTION_MULTIPLYING_NUMBERS_AS_STRINGS_H